version: "2"
services:
  node:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "80:3000"
    command: >
      bash -c "npm install && gulp build && npm run build && npm run start"
