# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('cart_id', models.IntegerField(db_column='Cart_id')),
                ('product_id', models.IntegerField(db_column='Product_id')),
            ],
            options={
                'db_table': 'Cart_Product',
                'managed': True,
            },
        ),
    ]
