# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_product', '0004_auto_20180311_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product'),
        ),
    ]
