# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_attribute', '0003_auto_20180406_2322'),
        ('cart_product', '0008_auto_20180312_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_product_attribute', to='product_attribute.ProductAttribute'),
        ),
    ]
