# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_product', '0009_cartproduct_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='attribute',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_product_attribute', to='product_attribute.ProductAttribute'),
        ),
    ]
