# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_column='Product_id')),
                ('exp_time', models.DateTimeField()),
                ('lastest_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_step', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Auction',
                'managed': False,
            },
        ),
    ]
