# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180311_1932'),
        ('auction', '0002_auto_20180311_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='product_id',
        ),
        migrations.AddField(
            model_name='auction',
            name='product',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='auction_product', to='product.Product'),
        ),
    ]
