# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0003_auto_20180312_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='customer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
