# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20180311_1921'),
        ('auction_customer', '0002_auto_20180311_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioncustomer',
            name='auction_id',
        ),
        migrations.AddField(
            model_name='auctioncustomer',
            name='auction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auction.Auction'),
        ),
    ]
