# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_customer', '0004_auto_20180312_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncustomer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
