---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
  name: {{ template "service_name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - {{ range $key, $val := . -}}
      {{ $key }}: {{ $val }}
      {{ end }}  
    {{- end }}
  selector:
    app: {{ template "name" . }}

{{- if .Values.service.haveHeadless }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    {{- range .Values.service.ports }}
    - {{ range $key, $val := . -}}
      {{ $key }}: {{ $val }}
      {{ end }}  
    {{- end }}
  selector:
    app: {{ template "name" . }}
{{- end }}
