# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180311_1921'),
        ('order', '0004_auto_20180312_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='customer.Customer'),
        ),
    ]
