# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180312_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slip',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
