# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180407_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
