# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_attribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
