# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'managed': True},
        ),
    ]
