# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_thumbnail'),
        ('product', '0004_remove_product_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='product_organization', to='organization.Organization'),
        ),
    ]
