# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180311_1921'),
        ('product', '0008_auto_20180312_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_customer', to='customer.Customer'),
        ),
    ]
