# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180312_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewer',
            field=models.IntegerField(default=0),
        ),
    ]
