# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180319_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product_category.ProductCategory'),
        ),
    ]
