# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('line_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('address', models.CharField(blank=True, max_length=1023, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('picture', models.CharField(max_length=1023)),
                ('order_count', models.IntegerField()),
                ('buy_count', models.IntegerField()),
                ('sell_count', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
    ]
