# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20180319_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='buy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sell_count',
            field=models.IntegerField(default=0),
        ),
    ]
