# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_organization_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPromptpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=32)),
                ('organization', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='organization_promptpay', to='organization.Organization')),
            ],
            options={
                'db_table': 'Organization_Promptpay',
                'managed': True,
            },
        ),
    ]
