# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True},
        ),
    ]
