# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180310_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='thumbnail',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
