# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
