# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
