# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180424_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='username',
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(default='', max_length=254),
        ),
    ]
