# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=32)),
                ('branch', models.CharField(max_length=255)),
                ('organization_id', models.IntegerField(db_column='Organization_id')),
                ('bank_id', models.IntegerField(db_column='Bank_id')),
            ],
            options={
                'db_table': 'Organization_Bank',
                'managed': False,
            },
        ),
    ]
