# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180311_1921'),
        ('organization_bank', '0003_auto_20180312_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationbank',
            name='bank_id',
        ),
        migrations.AddField(
            model_name='organizationbank',
            name='bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='organization_bank_bank', to='bank.Bank'),
        ),
    ]
