# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
        ('order_organization', '0002_auto_20180311_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderorganization',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderorganization',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_organization_order', to='order.Order'),
        ),
    ]
