# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_th', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('logo', models.CharField(max_length=1023)),
            ],
            options={
                'db_table': 'Bank',
                'managed': False,
            },
        ),
    ]
